name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Extractor
        - New Transformer
        - New Loader
        - Enhancement to existing component
        - Performance improvement
        - Data quality feature
        - Configuration option
        - Documentation
        - DevOps/CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component would this affect?
      multiple: true
      options:
        - Extractors
        - Transformers
        - Loaders
        - Pipeline Orchestration
        - Data Quality
        - Lineage Tracking
        - Configuration
        - Vault Integration
        - Logging/Observability
        - Performance/Benchmarking
        - Testing Framework
        - Documentation
        - Build/DevOps
        - Core Framework
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Provide an example of how you would use this feature
      placeholder: |
        ```yaml
        pipelineId: example
        source:
          type: new-source-type
          options:
            ...
        ```
      render: yaml

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: I also considered... but this doesn't work because...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: In my project, I need to...
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help test this feature
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Here's a similar feature in another project...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: This feature aligns with the project's goals
          required: true
